Heat the oven to 550°F or higher. Arrange a rack in the lower-middle part of the oven (if you have a baking stone, place it on the rack) and heat the oven to 550°F or higher. ...
Divide the dough in half. ...
Roll out the dough. ...
Top the pizza. ...
Bake the pizza. ...
Slice and serve.